pipeline:
    - test
    - build

jobs:
    test:
        series: focal
        architectures: amd64
        packages: [git]
        plugin: tox
    build:
        series: focal
        architectures: amd64
        plugin: pyproject-build
        output:
            paths:
                - "dist/*.tar.gz"
                - "dist/*.whl"
