# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        exclude: ^lib/contrib/
-   repo: https://github.com/PyCQA/isort
    rev: 5.10.0
    hooks:
    -   id: isort
-   repo: https://github.com/psf/black
    rev: 21.10b0
    hooks:
    -   id: black
-   repo: https://github.com/asottile/setup-cfg-fmt
    rev: v1.19.0
    hooks:
    -   id: setup-cfg-fmt
-   repo: https://github.com/jazzband/pip-tools
    rev: 6.4.0
    hooks:
    -   id: pip-compile
